### PR TITLE
fix(docs): change capsule helm repo url

### PR DESCRIPTION
**Pull request by ppeereb1**
Change helm repo url to the correct repo.

### CODE REVIEW

**Comment by oliverbaehler** [comment]
Hi @ppeereb1, I see you are fighting with helm-docs. Note: Just make the changes to `charts/capsule-proxy/README.md.gotmpl`. Then run `make helm-docs`, then your pipelines should become green.

**Review by oliverbaehler — APPROVED** [review]
LGTM, @ppeereb1 thanks for your contribution 🚀

**Comment by oliverbaehler** [comment]
@ppeereb1 whoops, your commits must be gpg signed, do you know how to do that?

**Comment by ppeereb1** [comment]
@oliverbaehler yes thanks for your help. I think now it's ok?

**Pull request merged**
