### PR TITLE
fix: allow wildcards on certificate generation

### LINKED ISSUE #523: helm chart (cert-manager) does not support wildcards
# Bug description

When enabling cert-manager for certificates, if you add a wildcard to the dns extra configuration it fails with 
```
Error: YAML parse error on capsule-proxy/templates/certmanager.yaml: error converting YAML to JSON: yaml: line 8: did not find expected alphabetic or numeric character
helm.go:84: [debug] error converting YAML to JSON: yaml: line 8: did not find expected alphabetic or numeric character
YAML parse error on capsule-proxy/templates/certmanager.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
	helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
	helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
	helm.sh/helm/v3/pkg/action/action.go:168
helm.sh/helm/v3/pkg/action.(*Install).RunWithContext
	helm.sh/helm/v3/pkg/action/install.go:312
main.runInstall
	helm.sh/helm/v3/cmd/helm/install.go:314
main.newTemplateCmd.func2
	helm.sh/helm/v3/cmd/helm/template.go:95
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.8.0/command.go:983
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.8.0/command.go:1115
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.8.0/command.go:1039
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:271
runtime.goexit
	runtime/asm_arm64.s:1222
```

# How to reproduce
use values:
```yaml
certManager:
  generateCertificates: true
  issuer:
    kind: Issuer
  certificate:
    includeInternalServiceNames: true
    dnsNames:
    - "*-proxy.capsule-system.svc"

```
# Expected behavior
It shoudl generate the certificate object with the proper wildcard in there

# Additional context

- Capsule-Proxy version: 0.7.1
- Helm Chart version: 0.7.1
- Kubernetes version: 1.28.9

### PR DESCRIPTION
**Pull request by ppodevlabs**
Fix #523

### CODE REVIEW

**Comment by prometherion** [comment]
As I commented in the issue linked to this PR, I think this doesn't work: wildcard domains require the DNS01 challenge.

May I ask you if you smoke-tested this change in your cluster?

**Review by prometherion — APPROVED** [review]

**Review by oliverbaehler — APPROVED** [review]

**Comment by oliverbaehler** [comment]
@ppodevlabs pls gpg sign all commits

**Comment by prometherion** [comment]
@ppodevlabs in case you missed last message by Oliver, thanks for the contribution!

**Comment by ppodevlabs** [comment]
> @ppodevlabs in case you missed last message by Oliver, thanks for the contribution!

sorry for the delay, i don't know where my notifications went... hehehe.

**Pull request merged**
